routes/web.php
<?php

use App\Http\Controllers\WishlistController;
use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Route;
use App\Models\Site;


// AJOUTER LES MIDDLEWARES SUR LES ROUTES DE MODIF DE PLAYLIST
//Routes necessitant d'etre auth
Route::middleware(['auth'])->group(function () {
    //Entry point
    Route::get('/', function () {return redirect()->route('wishlist.index');})->name('welcome');
    Route::get('/dump', function () {
        $price = SiteController::getAvailibility('taiwangun','https://www.taiwangun.com/fr/bille-020g-6mm/airsoft-bb-pellets-0-23g-bio-4350pcs-polished-precise-seamless-s-t');
         return view('dump',compact('price'));});

    Route::get('/sites/index',[SiteController::class,'index']);
    //Routes concernant les playlists
    Route::prefix('/wishlist')->name('wishlist.')->controller(WishlistController::class)->group(function(){
        Route::get('/index','index')->name('index');

        Route::get('/create','showCreate')->name('showCreate');
        Route::post('/create','create')->name('create');
        Route::get('/update/{wishlist}','showUpdate')->name('showUpdate');
        Route::post('/update/{wishlist}','update')->name('update');

        Route::get('/show/{wishlist}','show')->name('show');
        Route::post('/add_product/{wishlist}','addProduct')->name('addProduct');
        Route::get('/delete_product/{wishlist}/{product}','deleteProduct')->name('deleteProduct');


        //Route::get('/reset_musics/{playlist}','resetMusics')->name('reset_musics');
        // Route::get('/create','showCreate');

        // Route::post('/create','create');
        // Route::post('/update/{playlist}','update');
        });


    });

app/Models/Wishlist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
class Wishlist extends Model
{
    protected $fillable = [
        'name',
        'description',
        'owner_id',
        'room_key',
    ];
    use HasFactory;
    public function owner(): BelongsTo
    {
        return $this->belongsTo(User::class,'owner_id');
    }
    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/WishlistController.php
<?php

namespace App\Http\Controllers;

use App\Models\Wishlist;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Site;
use App\Http\Requests\ProductRequest;
use App\Models\Product;
use Barryvdh\Debugbar\Facades\Debugbar;
use Exception;
use App\Http\Requests\WishlistRequest;
class WishlistController extends Controller
{
    public function index(){
        $wishlists = Auth::user()->wishlists;
        return view('wishlist.index',compact('wishlists'));
    }
    public function show(Wishlist $wishlist, Request $request){
        $sites = Site::all();
        return view('wishlist.show',compact('wishlist','sites'));
    }

    public function showCreate(){
        $wishlist = new Wishlist();
        $wishlist->name = "Nom";
        $wishlist->description = "Description";
        return view('wishlist.create',compact('wishlist'));
    }
    public function showUpdate(Wishlist $wishlist){
        return view('wishlist.update',compact('wishlist'));
    }

    public function create(WishlistRequest $request){
        $wishlist = Wishlist::create($request->validated());
        //$wishlist->users()->save(Auth::user());
        return redirect()->route('wishlist.show',['wishlist' => $wishlist])->with('success',"La wishlist a bien été créée");

    }
    public function update(Wishlist $wishlist, WishlistRequest $request){
        $wishlist->update($request->validated());
        return redirect()->route('wishlist.show',['wishlist' => $wishlist])->with('success',"La wishlist a bien été modifiée");
    }




    public function addProduct(Wishlist $wishlist, ProductRequest $productRequest){
        $product = new Product();
        $product->url = $productRequest->validated()['url'];
        $product->priority = $productRequest->validated()['priority'];
        $product->site()->associate(Site::findOrfail($productRequest->validated()['site_id']));
        $product->wishlist()->associate($wishlist);

        try{
            $product->name = SiteController::getName($product->site->name,$product->url);
            $product->price = SiteController::getPrice($product->site->name,$product->url);
            $product->available = SiteController::getAvailibility($product->site->name,$product->url);
            $product->save();
            return  redirect()  ->route('wishlist.show',['wishlist' => $productRequest->validated()["wishlist_id"]])
                               ->with('success',"Le produit a bien été ajouté à la wishlist");
        }
        catch(Exception $e){
            return  redirect()  ->route('wishlist.show',['wishlist' => $productRequest->validated()["wishlist_id"]])
            ->with('error',"Une erreur est survenue");
        }

    }
    public function deleteProduct(Wishlist $wishlist, Product $product){
        $product->delete();
        return  redirect()  ->route('wishlist.show',['wishlist' => $wishlist])
        ->with('success',"Le produit a bien été suprimé de la wishlist");
    }
}

resources/views/wishlist/create.blade.php
@extends('layouts.app')

@section('page-title')
    Wishlist Creation
@endsection

@section('content')
    @include('wishlist.form')
@endsection


@section('css')
@endsection

@section('scripts')
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
@endsection

resources/views/wishlist/form.blade.php
<form method="post" class="vstack gap-2">
    @csrf
    <div class="form-group">
        <label for="name">Nom</label>
        <input type="string" class="form-control @error("name") is-invalid @enderror" id="name" name="name" value="{{ old('name', $wishlist->name) }}">
        @error("name")
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <input type="text" class="form-control @error("description") is-invalid @enderror" id="description" name="description" value="{{ old('description', $wishlist->description) }}">
        @error("description")
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
    </div>
    <button class="btn btn-primary">
        @if($wishlist->id)
            Modifier
        @else
            Creer
        @endif
    </button>
</form>

resources/views/wishlist/index.blade.php
@extends('layouts.app')

@section('page-title')
    Wishlists Dashboard
@endsection

@section('content')
<main role="main">

    <div class="album py-5 bg-light">
      <div class="container">

        <div class="row">


          @forelse ($wishlists as $wishlist)
            <div class="col-md-4">
                {{--Changer l'url ciblé !--}}
                <a class="text-reset text-decoration-none" href="show/{{$wishlist->id}}">

                    <div class="card mb-4">
                        <div class="card-body mb-3">
                          <h5 class="text-decoration-underline" class="card-text">{{$wishlist->name}}</h5>
                          {{--<p class="card-text">{{$wishlist->description}}</p>--}}
                          <div class="d-flex justify-content-between align-items-center">
                          </div>
                        </div>
                  </div>
                </a>
            </div>
          @empty
            <h3>Vous n'avez pas de wishlist</h3>
          @endforelse
            <a class="text-reset text-decoration-none" href={{ route('wishlist.create') }}>
                <div class="card mb-4">
                    <div class="card-body mb-3 text-center">
                      <h5 class="card-text">+</h5>
                      {{--<p class="card-text">{{$wishlist->description}}</p>--}}
                      <div class="d-flex justify-content-between align-items-center">
                      </div>
                    </div>
                </div>
            </a>
        </div>
      </div>
    </div>

  </main>
@endsection


@section('css')
@endsection

@section('scripts')
@endsection

resources/views/wishlist/show.blade.php
@extends('layouts.app')

@section('page-title')
    {{$wishlist->name}}
@endsection

@section('content')
<main class="d-block mx-auto">
    <a href='{{ route('wishlist.showUpdate', ["wishlist" => $wishlist]) }}'>
        <button class="btn btn-secondary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 16">
                <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
                <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"/>
              </svg>
        </button>
    </a>
    <table class="table table-bordered w-75 py-5 px-3">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Priority</th>
            <th scope="col">Site</th>
            <th scope="col">Disponible</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          @forelse ($wishlist->products as $product)
              <tr>
                <th scope="row">{{$product->name}}</th>
                <td>{{$product->price}}</td>
                <td>{{$product->priority}}</td>
                <td>{{$product->site->name}}</td>
                @if($product->available)
                    <td class='table-success table-bordered'></td>
                @else
                    <td class='table-danger'></td>
                @endif
                <td><a href='{{ route('wishlist.deleteProduct', ["wishlist" => $wishlist->id,"product"=> $product->id]) }}'><button class="btn btn-primary"> Delete </button></a></td>
              </tr>
          @empty

          @endforelse
        </tbody>
    </table>
    {{--Ajout de produit--}}
    <form  method='post' action='{{ route('wishlist.addProduct',$wishlist->id) }}'>
        @csrf
        <div class='card w-75 py-5 px-3'>
            <div class="form-group col-md-12 mt-3">
                <label for="product-url">Lien produit</label>
                <input type="text" name='url' class="form-control" id="product-url" placeholder="Entrer le lien du produit" value="{{ old('product-url') }}"/>
                @error('product-url')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
                @enderror
            </div>
            <div class="form-group col-md-12 mt-3">
                <label for="site-select">Site du produit</label>
                <select id='site-select' name='site_id' class="form-select">
                        <option selected>Select site</option>
                    @forelse ($sites as $site)
                        <option value="{{$site->id}}">{{$site->name}}</option>
                    @empty
                        <p>Probleme dans les sites disponibles rafraichissez</p>
                    @endforelse
                </select>
                @error('site-select')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="form-group col-md-12 mt-3">
                <label for="priority-select">Priorité du produit</label>
                <select id='priority-select' name='priority' class="form-select">
                        <option selected>1</option>
                    @for ($i=2;$i<=5;$i++)
                        <option value="{{$i}}">{{$i}}</option>
                    @endfor
                </select>
                @error('priority-select')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group col-md-12 mt-3">
                <button type="submit" class="btn btn-primary">Ajouter</button>
            </div>
        </div>
    </form>
</main>


@endsection

@section('css')
@endsection

@section('scripts')
    <script>
        window.onload=function () {
            document.getElementById('product-url').addEventListener("input", (event) => {
                var sites = document.getElementById('site-select').options;
                var i;
                for (i = 0; i < sites.length; i++) {
                    if(document.getElementById('product-url').value.includes(sites[i].text)) document.getElementById("site-select").value = sites[i].value;
                }
            });
        }



    </script>
@endsection

resources/views/wishlist/update.blade.php
@extends('layouts.app')

@section('page-title')
    Wishlist Update
@endsection

@section('content')
    @include('wishlist.form')
@endsection


@section('css')
@endsection

@section('scripts')
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
@endsection